export const emotes = [
  // Hearts & Love
  { name: "heart", symbol: "❤️" },
  { name: "orange_heart", symbol: "🧡" },
  { name: "yellow_heart", symbol: "💛" },
  { name: "green_heart", symbol: "💚" },
  { name: "blue_heart", symbol: "💙" },
  { name: "purple_heart", symbol: "💜" },
  { name: "black_heart", symbol: "🖤" },
  { name: "brown_heart", symbol: "🤎" },
  { name: "white_heart", symbol: "🤍" },
  { name: "broken_heart", symbol: "💔" },
  { name: "heart_exclamation", symbol: "❣️" },
  { name: "two_hearts", symbol: "💕" },
  { name: "revolving_hearts", symbol: "💞" },
  { name: "heartbeat", symbol: "💓" },
  { name: "heartpulse", symbol: "💗" },
  { name: "sparkling_heart", symbol: "💖" },
  { name: "cupid", symbol: "💘" },
  { name: "gift_heart", symbol: "💝" },
  { name: "heart_decoration", symbol: "💟" },
  
  // Hands & Gestures
  { name: "clap", symbol: "👏" },
  { name: "raised_hands", symbol: "🙌" },
  { name: "wave", symbol: "👋" },
  { name: "thumbsup", symbol: "👍" },
  { name: "thumbsdown", symbol: "👎" },
  { name: "punch", symbol: "👊" },
  { name: "fist", symbol: "✊" },
  { name: "victory", symbol: "✌️" },
  { name: "ok_hand", symbol: "👌" },
  { name: "pinching_hand", symbol: "🤏" },
  { name: "pray", symbol: "🙏" },
  
  // Symbols & Objects
  { name: "100", symbol: "💯" },
  { name: "trophy", symbol: "🏆" },
  { name: "medal", symbol: "🏅" },
  { name: "military_medal", symbol: "🎖️" },
  { name: "1st_place", symbol: "🥇" },
  { name: "2nd_place", symbol: "🥈" },
  { name: "3rd_place", symbol: "🥉" },
  { name: "star", symbol: "⭐" },
  { name: "glowing_star", symbol: "🌟" },
  { name: "sparkles", symbol: "✨" },
  { name: "dizzy", symbol: "💫" },
  { name: "boom", symbol: "💥" },
  { name: "fire", symbol: "🔥" },
  { name: "rocket", symbol: "🚀" },
  { name: "crown", symbol: "👑" },
  { name: "gem", symbol: "💎" },
  { name: "bell", symbol: "🔔" },
  { name: "tada", symbol: "🎉" },
  { name: "confetti", symbol: "🎊" },
  { name: "balloon", symbol: "🎈" },
  { name: "eyes", symbol: "👀" },
  { name: "check_mark", symbol: "✅" },
  { name: "x_mark", symbol: "❌" },
  { name: "warning", symbol: "⚠️" },
];
