export const emotes = [
  // Popular Twitch Emotes
  { name: "kappa", symbol: "Kappa" },
  { name: "pogchamp", symbol: "PogChamp" },
  { name: "lul", symbol: "LUL" },
  { name: "biblethump", symbol: "BibleThump" },
  { name: "kreygasm", symbol: "Kreygasm" },
  { name: "4head", symbol: "4Head" },
  { name: "failfish", symbol: "FailFish" },
  { name: "dansgame", symbol: "DansGame" },
  { name: "jebaited", symbol: "Jebaited" },
  { name: "trihard", symbol: "TriHard" },
  { name: "residentsleeper", symbol: "ResidentSleeper" },
  { name: "babyrage", symbol: "BabyRage" },
  { name: "wutface", symbol: "WutFace" },
  { name: "frankerz", symbol: "FrankerZ" },
  { name: "monkas", symbol: "monkaS" },
  { name: "pepehands", symbol: "PepeHands" },
  { name: "pepega", symbol: "Pepega" },
  { name: "omegalul", symbol: "OMEGALUL" },
  { name: "poggers", symbol: "POGGERS" },
  { name: "weirdchamp", symbol: "WeirdChamp" },
  { name: "peepopog", symbol: "PEEPOPOG" },
  { name: "sadge", symbol: "Sadge" },
  { name: "copium", symbol: "Copium" },
  { name: "kekw", symbol: "KEKW" },
  { name: "catjam", symbol: "CatJam" },
  { name: "peeposhy", symbol: "peepoShy" },
  { name: "peepoclap", symbol: "peepoClap" },
  { name: "pepega_clap", symbol: "PepegaClap" },
  { name: "5head", symbol: "5Head" },
  { name: "pausechamp", symbol: "PauseChamp" }
];