
INSERT INTO secret_shows_gifters (username, total_gifts, monthly_gifts, last_gift_date)
VALUES
  ('SunState Jon', 225, '{}', now()),
  ('Dj Rage', 24, '{}', now()),
  ('ajsoup', 23, '{}', now()),
  ('Catbutth0le', 23, '{}', now()),
  ('Juan Shawson', 22, '{}', now()),
  ('CraigK', 20, '{}', now()),
  ('Sam-e-Scam', 19, '{}', now()),
  ('Space_Coast_Native', 18, '{}', now()),
  ('D-RedEye', 18, '{}', now()),
  ('Phizzy', 15, '{}', now()),
  ('bro villa 1', 15, '{}', now()),
  ('TonyB.Greezy', 14, '{}', now()),
  ('Bobby B', 12, '{}', now()),
  ('Missy', 12, '{}', now()),
  ('numbRJ86', 12, '{}', now()),
  ('Sheepdawg', 11, '{}', now()),
  ('WaterBoys', 11, '{}', now()),
  ('Loose Neutral', 11, '{}', now()),
  ('Sean Patrick''s Day', 11, '{}', now()),
  ('Matthew Petit', 10, '{}', now()),
  ('fiebigsm', 10, '{}', now()),
  ('TheeStephApee', 10, '{}', now()),
  ('P F', 10, '{}', now()),
  ('Ardnas223', 9, '{}', now()),
  ('jeaninedm', 9, '{}', now()),
  ('Punishers420', 9, '{}', now()),
  ('Ryan_Annie', 7, '{}', now()),
  ('SGT Dave', 6, '{}', now()),
  ('buck has sex-a-ton', 6, '{}', now()),
  ('purple peepee eater', 6, '{}', now()),
  ('Cn JForge', 6, '{}', now()),
  ('Roadmap', 5, '{}', now()),
  ('nohairdontcare', 5, '{}', now()),
  ('The Sofa King', 5, '{}', now()),
  ('MelBell', 5, '{}', now()),
  ('azapico13', 5, '{}', now()),
  ('emefcue', 5, '{}', now()),
  ('MariaMac3', 5, '{}', now()),
  ('warpath77nnn', 5, '{}', now()),
  ('Giggles', 5, '{}', now()),
  ('Kilomack', 5, '{}', now()),
  ('HDafterbirth', 5, '{}', now()),
  ('DispatchDan', 5, '{}', now()),
  ('Cyclonis', 5, '{}', now()),
  ('Mankickin', 4, '{}', now()),
  ('The News Junkie', 4, '{}', now()),
  ('John the Exterminator', 4, '{}', now()),
  ('BootsyMoonshine', 4, '{}', now()),
  ('Nickz123', 4, '{}', now()),
  ('Joey Volvo', 3, '{}', now()),
  ('belinda1006', 3, '{}', now()),
  ('Big Digits', 3, '{}', now()),
  ('Tonya Morgan', 3, '{}', now()),
  ('Bambam2015', 3, '{}', now()),
  ('Avendesora', 3, '{}', now()),
  ('aksalis', 3, '{}', now()),
  ('V of many Trades', 2, '{}', now()),
  ('DeanaH', 2, '{}', now()),
  ('LisaG', 2, '{}', now()),
  ('aunt nette', 2, '{}', now()),
  ('Crikee', 2, '{}', now()),
  ('GagaJill', 2, '{}', now()),
  ('couchspyder', 2, '{}', now()),
  ('nick12292', 2, '{}', now()),
  ('AweSam', 2, '{}', now()),
  ('pig benis', 2, '{}', now()),
  ('Bri Bri', 2, '{}', now()),
  ('2Tickets2PoundTown', 2, '{}', now()),
  ('NOTRIGUY', 2, '{}', now()),
  ('Pattywhakk', 2, '{}', now()),
  ('Real Corn', 2, '{}', now()),
  ('NoVa Doug', 2, '{}', now()),
  ('Sam I am', 2, '{}', now()),
  ('Justinmrrd', 2, '{}', now()),
  ('GoochWillKill', 2, '{}', now()),
  ('JacksonJill', 2, '{}', now()),
  ('SharkBait', 1, '{}', now()),
  ('deliverypenguin', 1, '{}', now()),
  ('NiNi', 1, '{}', now()),
  ('fester99', 1, '{}', now()),
  ('jessekr', 1, '{}', now()),
  ('Bebkkrane', 1, '{}', now()),
  ('bigballerbarr', 1, '{}', now()),
  ('Johndeerejoey', 1, '{}', now()),
  ('Matt J Wil', 1, '{}', now()),
  ('Kel kel', 1, '{}', now()),
  ('MannyPest', 1, '{}', now()),
  ('smackrel', 1, '{}', now()),
  ('stevearaica2015@gmail.com', 1, '{}', now()),
  ('C_LO456NYS', 1, '{}', now()),
  ('Jaquanolicous', 1, '{}', now()),
  ('AA-ron', 1, '{}', now()),
  ('Pug32837', 1, '{}', now()),
  ('Stone707', 1, '{}', now()),
  ('ElectricDivaCreations', 1, '{}', now()),
  ('Swilly', 1, '{}', now()),
  ('Godless heathen', 1, '{}', now()),
  ('Divotseesall', 1, '{}', now()),
  ('SPILI', 1, '{}', now()),
  ('TravelingSuperintendent', 1, '{}', now()),
  ('Trucker', 1, '{}', now()),
  ('RockinAng', 1, '{}', now()),
  ('VONRIPPERTON', 1, '{}', now()),
  ('VicG', 1, '{}', now()),
  ('Wildfire98', 1, '{}', now()),
  ('abraham_dragonfriend', 1, '{}', now()),
  ('Regina_Phalange10', 1, '{}', now()),
  ('Feral Kitten', 1, '{}', now()),
  ('DrDru', 1, '{}', now())
ON CONFLICT (username) DO UPDATE SET
  total_gifts = EXCLUDED.total_gifts,
  updated_at = now();
